var orderHistory = [
  {
    orderList: 1,
    orderNumber: '114-3941689-8772232',
    orderDate: 'August 4, 2020',
    grandTotal: 34,
    shipTo: 'JS Masher',
    numberOfItems: 1,
    deliveredDate: 'August 8, 2020',
    deliveredMemo: null,
    productName: 'JavaScript for impatient programmers',
    author: 'Dr Axel Rauschmayer',
    returnDeadline: 'September 7, 2020',
    deadlinePast: false,
    subtotal: 31.55,
    productSupport: false
  },
  {
    orderList: 2,
    orderNumber: '113-9984268-1280257',
    orderDate: 'July 19, 2020',
    grandTotal: 44.53,
    shipTo: 'JS Masher',
    numberOfItems: 1,
    deliveredDate: 'July 20, 2020',
    deliveredMemo: 'Your package was delivered. It was handed directly to a resident.',
    productName: 'The Timeless Way of Building',
    author: 'Christopher Alexander',
    returnDeadline: 'August 19, 2020',
    deadlinePast: false,
    subtotal: 41.33,
    productSupport: false
  },
  {
    orderList: 3,
    orderNumber: '114-28755557-9059409',
    orderDate: 'July 4, 2020',
    grandTotal: 17.22,
    shipTo: 'JS Masher',
    numberOfItems: 1,
    deliveredDate: 'July 7, 2020',
    deliveredMemo: 'Your package was delivered.It was handed directly to a resident.',
    productName: 'Gamecube Controller Adapter, Super Smash Bros Switch Gamecube Adapter for WII U, PC. Support Turbo and Vibration Features. No Driver and No Lag-Gamecube Adapter',
    author: null,
    returnDeadline: 'August 5, 2020',
    deadlinePast: true,
    subtotal: 15.98,
    productSupport: false
  },
  {
    orderList: 4,
    orderNumber: '113-2883177-2648248',
    orderDate: 'July 3, 2020',
    grandTotal: 138.93,
    shipTo: 'JS Masher',
    numberOfItems: 2,
    deliveredDate: ['July 5,2020', 'July 5 2020'],
    deliveredMemo: [null, null],
    productName: ['GameCube Controller - Super Smash Bros. Edition (Nintendo Switch)', 'The Art of Sql'],
    author: [null, 'Stephane Faroult'],
    returnDeadline: ['August 4, 2020', 'August 4 2020'],
    deadlinePast: [true, true],
    subtotal: [94.95, 33.99],
    productSupport: true
  }
];
